name: 'Bench'
on:
  workflow_dispatch:
jobs:
  Bench:
    name: 'Bench Job'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Exe
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST_BENCH }}
          username: isucon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo -u isucon /home/isucon/private_isu.git/benchmarker/bin/benchmarker -u /home/isucon/private_isu.git/benchmarker/userdata -t http://${{ vars.HOST1 }}
