name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

          ssh isucon@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/isucon  # アプリケーションのディレクトリに移動
            git pull origin master  # リモートリポジトリから最新のコードを取得
            # 必要に応じてビルドや再起動のコマンドを追加
            # 例: npm install && npm run build
            # 例: sudo systemctl restart your-service
          EOF
